[0m10:34:56.893361 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023588917DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002358B34E3B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002358B34E1D0>]}


============================== 10:34:56.903436 | f51753a2-b68c-4784-b6ff-9ae83862bd90 ==============================
[0m10:34:56.903436 [info ] [MainThread]: Running with dbt=1.7.9
[0m10:34:56.903436 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\MananJain\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:34:56.903436 [info ] [MainThread]: dbt version: 1.7.9
[0m10:34:56.903436 [info ] [MainThread]: python version: 3.10.0
[0m10:34:56.903436 [info ] [MainThread]: python path: C:\Users\MananJain\AppData\Local\Programs\Python\Python310\python.exe
[0m10:34:56.903436 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m10:34:57.237038 [info ] [MainThread]: Using profiles dir at C:\Users\MananJain\.dbt
[0m10:34:57.237038 [info ] [MainThread]: Using profiles.yml file at C:\Users\MananJain\.dbt\profiles.yml
[0m10:34:57.237038 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\MananJain\Desktop\Login\dbt_project.yml
[0m10:34:57.245125 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m10:34:57.247151 [debug] [MainThread]: Command `dbt debug` failed at 10:34:57.247151 after 0.51 seconds
[0m10:34:57.247151 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023588917DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002358B34D0C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002358B34E3E0>]}
[0m10:34:57.247151 [debug] [MainThread]: Flushing usage events
[0m10:36:00.916740 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011322237DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011324C5E350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011324C5E170>]}


============================== 10:36:00.932400 | 7b35975c-f4bc-4cfb-9108-c84e6b3f9c77 ==============================
[0m10:36:00.932400 [info ] [MainThread]: Running with dbt=1.7.9
[0m10:36:00.932400 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\MananJain\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:36:00.932400 [info ] [MainThread]: dbt version: 1.7.9
[0m10:36:00.932400 [info ] [MainThread]: python version: 3.10.0
[0m10:36:00.932400 [info ] [MainThread]: python path: C:\Users\MananJain\AppData\Local\Programs\Python\Python310\python.exe
[0m10:36:00.932400 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m10:36:01.195428 [info ] [MainThread]: Using profiles dir at C:\Users\MananJain\.dbt
[0m10:36:01.195428 [info ] [MainThread]: Using profiles.yml file at C:\Users\MananJain\.dbt\profiles.yml
[0m10:36:01.195428 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\MananJain\Desktop\Login\dbt_project.yml
[0m10:36:01.195428 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m10:36:01.195428 [debug] [MainThread]: Command `dbt debug` failed at 10:36:01.195428 after 0.38 seconds
[0m10:36:01.195428 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011322237DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011324C5E500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011324C5E230>]}
[0m10:36:01.195428 [debug] [MainThread]: Flushing usage events
