[0m17:16:25.493707 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026402767DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002640515E350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002640515E170>]}


============================== 17:16:25.501705 | d0fc800f-e5e7-47bf-b2e9-11faa4601b1c ==============================
[0m17:16:25.501705 [info ] [MainThread]: Running with dbt=1.7.9
[0m17:16:25.502708 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\MananJain\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:16:39.410480 [debug] [MainThread]: Starter project path: C:\Users\MananJain\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\include\starter_project
[0m17:16:39.491481 [info ] [MainThread]: 
Your new dbt project "ETMS" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:16:39.492480 [info ] [MainThread]: Setting up your profile.
[0m17:16:43.277196 [info ] [MainThread]: No sample profile found for sqlserver.
[0m17:16:43.279198 [debug] [MainThread]: Command `dbt init` succeeded at 17:16:43.279198 after 17.89 seconds
[0m17:16:43.280200 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026402767DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002640515F1C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002640515E3E0>]}
[0m17:16:43.280200 [debug] [MainThread]: Flushing usage events
[0m17:16:56.961968 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013AF4517DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013AF6F3E350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013AF6F3E170>]}


============================== 17:16:56.967969 | c557207b-bac3-4a65-98a6-f452fb3516e6 ==============================
[0m17:16:56.967969 [info ] [MainThread]: Running with dbt=1.7.9
[0m17:16:56.969970 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\MananJain\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:16:56.970968 [info ] [MainThread]: dbt version: 1.7.9
[0m17:16:56.971970 [info ] [MainThread]: python version: 3.10.0
[0m17:16:56.972968 [info ] [MainThread]: python path: C:\Users\MananJain\AppData\Local\Programs\Python\Python310\python.exe
[0m17:16:56.973968 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m17:16:57.327965 [info ] [MainThread]: Using profiles dir at C:\Users\MananJain\.dbt
[0m17:16:57.328967 [info ] [MainThread]: Using profiles.yml file at C:\Users\MananJain\.dbt\profiles.yml
[0m17:16:57.330970 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\MananJain\Desktop\Login\DATA\DBT\dbt_project.yml
[0m17:16:57.331968 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m17:16:57.333968 [debug] [MainThread]: Command `dbt debug` failed at 17:16:57.333968 after 0.50 seconds
[0m17:16:57.334970 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013AF4517DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013AF6F3E230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013AF6F3D0C0>]}
[0m17:16:57.335968 [debug] [MainThread]: Flushing usage events
[0m17:18:13.740694 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018609A17DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001860C44E380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001860C44E1A0>]}


============================== 17:18:13.745693 | e5cd86f5-b0e9-4ba0-99f3-ef7974f7c3dd ==============================
[0m17:18:13.745693 [info ] [MainThread]: Running with dbt=1.7.9
[0m17:18:13.746694 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\MananJain\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:18:13.747694 [info ] [MainThread]: dbt version: 1.7.9
[0m17:18:13.748694 [info ] [MainThread]: python version: 3.10.0
[0m17:18:13.749701 [info ] [MainThread]: python path: C:\Users\MananJain\AppData\Local\Programs\Python\Python310\python.exe
[0m17:18:13.750695 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m17:18:14.066707 [info ] [MainThread]: Using profiles dir at C:\Users\MananJain\.dbt
[0m17:18:14.067700 [info ] [MainThread]: Using profiles.yml file at C:\Users\MananJain\.dbt\profiles.yml
[0m17:18:14.068691 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\MananJain\Desktop\Login\DATA\DBT\dbt_project.yml
[0m17:18:14.070588 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m17:18:14.072613 [debug] [MainThread]: Command `dbt debug` failed at 17:18:14.072613 after 0.43 seconds
[0m17:18:14.072613 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018609A17DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001860C44E530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001860C44E260>]}
[0m17:18:14.073598 [debug] [MainThread]: Flushing usage events
[0m17:18:29.101799 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025BFDC63D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B80835A80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B808358A0>]}


============================== 17:18:29.106799 | 5f0c0930-4dad-4aa8-b840-e64971ddba86 ==============================
[0m17:18:29.106799 [info ] [MainThread]: Running with dbt=1.7.9
[0m17:18:29.107799 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\MananJain\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:18:29.108800 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\MananJain\Desktop\Login\DATA\DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:18:29.111800 [debug] [MainThread]: Command `dbt run` failed at 17:18:29.110807 after 0.10 seconds
[0m17:18:29.111800 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025BFDC63D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B80835A20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025B80835B10>]}
[0m17:18:29.112801 [debug] [MainThread]: Flushing usage events
